- name: plugin install
  yum: name={{ item }} 
  with_items:
    - git
    #コンパイル用コマンド
    - make
    #コンパイラ
    - gcc-c++
    #パッチ適用コマンド
    - patch
    #OpenSSL用ファイル
    - openssl-devel
    #Ruby用パッケージ/アプリ開発用ライブラリ
    - libyaml-devel
    - libffi-devel 
    - libicu-devel
    - libxml2
    - libxslt
    - libxml2-devel
    - libxslt-devel
    - zlib-devel
    - readline-devel

- name: mysql GPG install/  add repo
  #MySQL公式のyumリポジトリを追加/GPGキーのインストール
  shell: rpm -ivh http://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm;
         rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022;

- name: mysql install
  #mysql clientインストール
  yum: name=mysql-community-client

- name: Download nvm install.sh
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh
    dest: /var/tmp
    mode: 0755
 
- name: install.sh
  become_user: site-user
  shell: /var/tmp/install.sh
 
- name: source nvm.sh
  become_user: site-user
  shell: source /home/site-user/.nvm/nvm.sh && nvm install v15.5.0 && nvm alias default 15.5.0;

- name: rbenv install
  #rubyのバージョン管理ツールをインストール/パスを通し、shims と autocompletion の有効化設定を追記/設定反映
  become_user: site-user
  git: 
    repo: https://github.com/sstephenson/rbenv.git
    dest: ~/.rbenv

- name: path rbenv
  become_user: site-user
  lineinfile:
      dest: ~/.bash_profile
      line: '{{ item }}'
  with_items:
    - PATH="$HOME/.rbenv/bin:$PATH"
    - eval "$(rbenv init -)"

- name: source rbenv
  become_user: site-user
  shell: source ~/.bash_profile

- name: ruby-build  install
  #rubyのビルドツールをインストール/ ~/.rbenv/versions/*/bin/ 以下のファイルを ~/.rbenv/shims/ 以下にコピー
  become_user: site-user
  git: 
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build

- name: rbenv rehash
  become_user: site-user
  shell: bash -lc "rbenv rehash"

- name: ruby install
  become_user: site-user
  shell: bash -lc "rbenv install -v 2.6.5";
         bash -lc "rbenv global 2.6.5";
         bash -lc "rbenv rehash";
