- name: plugin install
  yum: name={{ item }} 
  with_items:
    - git
    #コンパイル用コマンド
    - make
    #コンパイラ
    - gcc-c++
    #パッチ適用コマンド
    - patch
    #OpenSSL用ファイル
    - openssl-devel
    #Ruby用パッケージ/アプリ開発用ライブラリ
    - libyaml-devel
    - libffi-devel 
    - libicu-devel
    - libxml2
    - libxslt
    - libxml2-devel
    - libxslt-devel
    - zlib-devel
    - readline-devel

- name: mysql GPG install/  add repo
  #MySQL公式のyumリポジトリを追加/GPGキーのインストール
  shell: rpm -ivh http://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm;
         rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022;

- name: mysql install
  #mysql clientインストール
  yum: name={{ item }}
  with_items:
    - mysql-community-client
    - mysql-devel

- name: check file nvm installer
  stat:
    path: /var/tmp/install.sh
  register: nvm_installer

- name: Download nvm install.sh
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh
    dest: /var/tmp
    mode: 0755
  when: not nvm_installer.stat.exists

- name: install.sh
  become_user: site-user
  shell: /var/tmp/install.sh

- name: source nvm.sh
  become_user: site-user
  shell: source /home/site-user/.nvm/nvm.sh && nvm install v15.5.0 && nvm alias default 15.5.0;

- name: check directory rbenv
  become_user: site-user
  stat:
    path: ~/.rbenv
  register: rbenv

- name: rbenv install
  #rubyのバージョン管理ツールをインストール/パスを通し、shims と autocompletion の有効化設定を追記/設定反映
  become_user: site-user
  git: 
    repo: https://github.com/sstephenson/rbenv.git
    dest: ~/.rbenv
  when: not rbenv.stat.exists

- name: path rbenv
  become_user: site-user
  lineinfile:
      dest: ~/.bash_profile
      line: '{{ item }}'
  with_items:
    - PATH="$HOME/.rbenv/bin:$PATH"
    - eval "$(rbenv init -)"

- name: source rbenv
  become_user: site-user
  shell: source ~/.bash_profile
  when: not rbenv.stat.exists

- name: check directory ruby-build
  become_user: site-user
  stat:
    path: ~/.rbenv/plugins/ruby-build
  register: rbuild

- name: ruby-build  install
  #rubyのビルドツールをインストール/ ~/.rbenv/versions/*/bin/ 以下のファイルを ~/.rbenv/shims/ 以下にコピー
  become_user: site-user
  git: 
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
  when: not rbuild.stat.exists

- name: rbenv rehash
  become_user: site-user
  shell: bash -lc "rbenv rehash"
  when: not rbuild.stat.exists

- name: インストール対象のバージョンのrubyがインストール済か確認
  become_user: site-user
  shell: bash -lc "rbenv versions | grep 2.6.5"
  register: rbenv_check_install
  changed_when: False
  ignore_errors: yes

- name: ruby install
  become_user: site-user
  shell: bash -lc "rbenv install -v 2.6.5";
         bash -lc "rbenv global 2.6.5";
         bash -lc "rbenv rehash";
  when: rbenv_check_install is failed

- name: check directory app
  become_user: site-user
  stat:
    path: /var/www/rails
  register: app

- name: make directory
  file: path=/var/www/rails
        state=directory
        owner=site-user
        group=site-user
        mode=0755
  when: not app.stat.exists
