---
- name: create /etc/modules-load.d/k8s.conf
  copy:
    src: modules_k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: 0644

- name: modules load
  shell: modprobe overlay;
         modprobe br_netfilter;

- name: create /etc/sysctl.d/k8s.conf
  copy:
    src: sysctl_k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0644

- name: modify kernel paramater
  shell: sysctl --system
