---
- hosts: all
  become: yes
  roles:
    - common_infra/kubeadm_containerd
    - common_infra/kubeadm_kube
    - common_infra/kubeadm_controlplane
  vars_prompt:
    - name: "controlplane_public_ip"
      prompt: "controlplaneノードのパブリックIPアドレスを入力"
      private: no
