- name: install tigera-operator
  shell: sudo -u ubuntu kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/tigera-operator.yaml;
- name: install calico
  shell: sudo -u ubuntu kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/custom-resources.yaml;sleep 60;
