---
- name: check file /etc/kubernetes/admin.conf
  stat:
    path: /etc/kubernetes/admin.conf
  register: admin_config

- include_tasks: prepare.yml
  when: not admin_config.stat.exists

- include_tasks: initialize.yml
  when: not admin_config.stat.exists

- include_tasks: calico.yml
  when: not admin_config.stat.exists

- include_tasks: set_kubelet.yml
  when: not admin_config.stat.exists
