# kubeadmで構築する場合のplaybook

---
- hosts: all
  become: yes
  roles:
    - ankiba/containerd
    - ankiba/kube
    - ankiba/controlplane
  vars_prompt:
    - name: "controlplane_public_ip"
      prompt: "controlplaneノードのパブリックIPアドレスを入力"
      private: no
