- name: download alertmanager
  shell: wget https://github.com/prometheus/alertmanager/releases/download/v0.27.0/alertmanager-0.27.0.linux-amd64.tar.gz

- name: deploy tar ball
  shell: tar xvfz alertmanager-0.27.0.linux-amd64.tar.gz