---
- name: check installation status
  shell: apt list --installed 2>/dev/null | grep kubelet
  register: kubelet_is_installed
  ignore_errors: True
  changed_when: False

- include_tasks: prepare.yml
  when: kubelet_is_installed.stdout == ""

- include_tasks: install.yml
  when: kubelet_is_installed.stdout == ""
