- name: apt update
  apt:
    update_cache: yes

- name: install apt-transport-https ca-certificates curl
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl

- name: swap off
  shell: swapoff -a;
         (crontab -l 2>/dev/null; echo "@reboot /sbin/swapoff -a") | crontab - || true;

- name: Add Kubernetes's official GPG key
  shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg;

- name: Add the repository to Apt sources
  shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

