- name: create mysql database
  mysql_db:
    login_user: root
    login_host: localhost
    login_password: "{{ mysql_password }}"
    name: ankiba
    state: present

- name: create mysql user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_password }}"
    login_host: localhost
    name: "{{ mysql_user }}"
    host: "{{ mysql_host }}"
    password: "{{ mysql_password }}"
    priv: ankiba.*:ALL,GRANT
    state: present
