- name: mysql GPG install/  add repo
  #MySQL公式のyumリポジトリを追加/GPGキーのインストール
  shell: rpm -ivh http://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm;
         rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022;

- name: epel install
  shell: amazon-linux-extras install -y epel

- name: mysql install
  #mysql インストール
  yum: name={{ item }}
  with_items:
    - mysql-community-server
    - mysql-devel
    - python2-PyMySQL.noarch 

- name: my.cnf
  copy:
    src: my.cnf
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644

- name: mysql restart
  service:
    name: mysqld
    state: restarted

- name: create mysql database
  mysql_db: name=memory_tank state=present

- name: pass reset
  shell: mysql -uroot -e "flush privileges; alter user 'root'@'localhost' identified by '{{ mysql_password  }}';"

- name: create mysql user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_password }}"
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "{{ host }}"
    priv: memory_tank.*:ALL,GRANT
    state: present

- name: Delete Line
  lineinfile:
    dest: /etc/my.cnf
    regexp: skip-grant-tables
    state: absent

- name: mysql restart
  service:
    name: mysqld
    state: restarted
