- name: vi Gemfile
  blockinfile:
      path: /var/www/rails/memory_tank/Gemfile
      block: |
        group :production, :staging do
            gem 'unicorn'
        end
        gem 'dotenv-rails'

- name: gem bundler install
  become_user: site-user
  shell: /bin/bash -lc "gem install bundler"

- name: bundle install
  become_user: site-user
  shell: cd /var/www/rails/memory_tank;
         /bin/bash -lc "bundle install";

- name: unicorn.conf
  copy:
    src: unicorn.conf.rb
    dest: /var/www/rails/memory_tank/config/unicorn.conf.rb
    owner: site-user
    group: site-user
    mode: 0644
