- name: vi Gemfile
  blockinfile:
      path: /var/www/rails/memory_tank/Gemfile
      block: |
        group :production, :staging do
            gem 'unicorn'
        end
        gem 'dotenv-rails'

- name: 'bundlerインストール'
  gem:
    name: bundler
    user_install: no
    executable: /home/site-user/.rbenv/shims/gem

- name: unicorn.conf
  copy:
    src: unicorn.conf.rb
    dest: /var/www/rails/memory_tank/config/unicorn.conf.rb
    owner: site-user
    group: site-user
    mode: 0644
