---
- hosts: webap_servers
  become: yes
  vars_files:
    - user-list.yml
  tasks:
  - name: add user
    user:
      name: "{{ item.name }}"
      password: "{{ item.password }}"
      groups:  "{{ item.group }}"
      shell: /bin/bash
    with_items:
      - "{{ users }}"
    when: users