- name: nginx.conf
  copy:
    src: ankiba.conf
    dest: /etc/nginx/conf.d/ankiba.conf
    owner: root
    group: root
    mode: 0644

- name: nginx restart
  service:
    name: nginx
    state: restarted
